#!/bin/bash
# SkyCast Weather Station - Raspberry Pi Installer
# One-line installer for Raspberry Pi OS

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
PROJECT_NAME="SkyCast Weather Station"
VERSION="3.0.0"
REPO_URL="https://github.com/yourusername/weather-station.git"
INSTALL_DIR="/opt/skycast"
SYSTEM_USER="skycast"
SERVICE_NAME="skycast"

echo -e "${BLUE}╔════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║   ${PROJECT_NAME} v${VERSION} - Installer          ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════╝${NC}"
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}Error: Please run as root (sudo ./install.sh)${NC}"
    exit 1
fi

# Detect Raspberry Pi model
echo -e "${YELLOW}Detecting hardware...${NC}"
if [ -f /proc/device-tree/model ]; then
    PI_MODEL=$(cat /proc/device-tree/model)
    echo -e "${GREEN}✓ Detected: $PI_MODEL${NC}"
else
    echo -e "${YELLOW}⚠ Not running on Raspberry Pi (will use mock hardware)${NC}"
fi

# Create system user
echo -e "${YELLOW}Creating system user...${NC}"
if ! id "$SYSTEM_USER" &>/dev/null; then
    useradd -r -s /bin/false -d "$INSTALL_DIR" "$SYSTEM_USER"
    echo -e "${GREEN}✓ Created user: $SYSTEM_USER${NC}"
else
    echo -e "${GREEN}✓ User already exists: $SYSTEM_USER${NC}"
fi

# Create installation directory
echo -e "${YELLOW}Setting up installation directory...${NC}"
mkdir -p "$INSTALL_DIR"
chown "$SYSTEM_USER:$SYSTEM_USER" "$INSTALL_DIR"
chmod 755 "$INSTALL_DIR"

# Install system dependencies
echo -e "${YELLOW}Installing system dependencies...${NC}"
apt-get update -qq
apt-get install -y -qq \
    python3 \
    python3-pip \
    python3-venv \
    git \
    i2c-tools \
    libi2c-dev \
    >/dev/null 2>&1
echo -e "${GREEN}✓ System dependencies installed${NC}"

# Clone or update repository
cd "$INSTALL_DIR"
if [ -d ".git" ]; then
    echo -e "${YELLOW}Updating existing installation...${NC}"
    git pull --quiet
else
    echo -e "${YELLOW}Cloning repository...${NC}"
    git clone --quiet "$REPO_URL" .
fi
echo -e "${GREEN}✓ Source code ready${NC}"

# Create virtual environment
echo -e "${YELLOW}Creating Python virtual environment...${NC}"
python3 -m venv venv
chown -R "$SYSTEM_USER:$SYSTEM_USER" venv
echo -e "${GREEN}✓ Virtual environment created${NC}"

# Install Python dependencies
echo -e "${YELLOW}Installing Python dependencies...${NC}"
source venv/bin/activate
pip install --upgrade pip --quiet
pip install -e . --quiet
echo -e "${GREEN}✓ Python dependencies installed${NC}"

# Create config directory
echo -e "${YELLOW}Setting up configuration...${NC}"
mkdir -p "$INSTALL_DIR/config"
chown "$SYSTEM_USER:$SYSTEM_USER" "$INSTALL_DIR/config"

# Create default .env if not exists
if [ ! -f "$INSTALL_DIR/.env" ]; then
    cat > "$INSTALL_DIR/.env" << EOF
# SkyCast Weather Station Configuration
# Generated by installer on $(date)

# Location (default: Kuwait City)
WEATHER_LATITUDE=29.325390
WEATHER_LONGITUDE=48.019562

# Units
WEATHER_UNIT=C
WEATHER_LANGUAGE=en

# Hardware
WEATHER_BUZZER_MODE=ALL

# Discord (optional - get token from https://discord.com/developers/applications)
# WEATHER_DISCORD_TOKEN=your_bot_token_here
# WEATHER_DISCORD_CHANNEL_ID=1234567890

# Timing (minutes)
WEATHER_API_RATE=10
WEATHER_LOG_RATE=15

# Web Server
WEATHER_WEB_HOST=0.0.0.0
WEATHER_WEB_PORT=8000

# UI
WEATHER_THEME=auto
EOF
    chown "$SYSTEM_USER:$SYSTEM_USER" "$INSTALL_DIR/.env"
    chmod 600 "$INSTALL_DIR/.env"
    echo -e "${GREEN}✓ Default configuration created${NC}"
else
    echo -e "${GREEN}✓ Configuration already exists${NC}"
fi

# Create systemd service
echo -e "${YELLOW}Installing systemd service...${NC}"
cat > "/etc/systemd/system/${SERVICE_NAME}.service" << EOF
[Unit]
Description=${PROJECT_NAME}
After=network.target i2c.service

[Service]
Type=simple
User=$SYSTEM_USER
Group=$SYSTEM_USER
WorkingDirectory=$INSTALL_DIR
Environment="PATH=$INSTALL_DIR/venv/bin"
ExecStart=$INSTALL_DIR/venv/bin/python -m weather_station.main
Restart=on-failure
RestartSec=10

# Security hardening
NoNewPrivileges=true
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable "$SERVICE_NAME" --quiet
echo -e "${GREEN}✓ Systemd service installed and enabled${NC}"

# Enable I2C interface
echo -e "${YELLOW}Enabling I2C interface...${NC}"
if command -v raspi-config &> /dev/null; then
    raspi-config nonint do_i2c 0 || true
fi
modprobe i2c-dev || true
echo -e "${GREEN}✓ I2C interface enabled${NC}"

# Set permissions
echo -e "${YELLOW}Setting permissions...${NC}"
chown -R "$SYSTEM_USER:$SYSTEM_USER" "$INSTALL_DIR"
chmod +x "$INSTALL_DIR/venv/bin/skycast" 2>/dev/null || true
echo -e "${GREEN}✓ Permissions configured${NC}"

# Final summary
echo ""
echo -e "${GREEN}╔════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║              Installation Complete! ✓                  ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${BLUE}Installation Summary:${NC}"
echo -e "  • Version: ${VERSION}"
echo -e "  • Install Dir: ${INSTALL_DIR}"
echo -e "  • Service: ${SERVICE_NAME}.service"
echo -e "  • Web UI: http://<your-pi-ip>:8000"
echo ""
echo -e "${YELLOW}Next Steps:${NC}"
echo -e "  1. Edit configuration: ${YELLOW}sudo nano $INSTALL_DIR/.env${NC}"
echo -e "  2. Start the service: ${YELLOW}sudo systemctl start $SERVICE_NAME${NC}"
echo -e "  3. Check status: ${YELLOW}sudo systemctl status $SERVICE_NAME${NC}"
echo -e "  4. View logs: ${YELLOW}sudo journalctl -u $SERVICE_NAME -f${NC}"
echo ""
echo -e "${BLUE}Useful Commands:${NC}"
echo -e "  • Start: ${YELLOW}sudo systemctl start $SERVICE_NAME${NC}"
echo -e "  • Stop: ${YELLOW}sudo systemctl stop $SERVICE_NAME${NC}"
echo -e "  • Restart: ${YELLOW}sudo systemctl restart $SERVICE_NAME${NC}"
echo -e "  • Enable at boot: ${YELLOW}sudo systemctl enable $SERVICE_NAME${NC}"
echo -e "  • Disable at boot: ${YELLOW}sudo systemctl disable $SERVICE_NAME${NC}"
echo ""
echo -e "${BLUE}Discord Bot Setup:${NC}"
echo -e "  1. Create bot at: https://discord.com/developers/applications"
echo -e "  2. Copy bot token to: ${YELLOW}$INSTALL_DIR/.env${NC}"
echo -e "  3. Restart service: ${YELLOW}sudo systemctl restart $SERVICE_NAME${NC}"
echo -e "  4. Use /setup in Discord to configure"
echo ""
echo -e "${GREEN}Thank you for installing SkyCast Weather Station!${NC}"
echo ""
